apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rabbitmq-cluster
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - list:
        elements:
          - env: consumer-producer
            url: https://kubernetes.default.svc
            branch: consumer-producer
            type: cluster-instance
          - env: consumer-producer
            url: https://kubernetes.default.svc
            branch: consumer-producer
            type: configuration
  template:
    metadata:
      name: "rabbitmq-{{type}}-{{env}}"
    spec:
      project: rabbitmq
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        # URL of the repository
        repoURL: https://github.com/LeitnerMi/rabbitmq-poc-gitops.git
        # Revision (tag/branch/commit) of the repository (eg HEAD)
        targetRevision: "{{ branch }}"
        # Path within the repository where Kubernetes manifests (and/or Helm, Kustomize, Jsonnet resources) are located
        path: rabbitq/{{ type }}/{{ env }}
      destination:
        server: "{{url}}"
        namespace: "rabbitmq-{{env}}"
