apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rabbitmq-cluster-instance
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - list:
        elements:
          - url: https://kubernetes.default.svc
            branch: main
  template:
    metadata:
      name: "rabbitmq-instance-{{ branch }}"
      annotations:
        rabbitmq.com/topology-allowed-namespaces: "*-app-{{ branch }}"
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        # URL of the repository
        repoURL: https://github.com/LeitnerMi/rabbitmq-poc-gitops.git
        # Revision (tag/branch/commit) of the repository (eg HEAD)
        targetRevision: "{{ branch }}"
        # Path within the repository where Kubernetes manifests (and/or Helm, Kustomize, Jsonnet resources) are located
        path: "cluster-instance/env/{{ branch }}"
      destination:
        server: "{{ url }}"
        namespace: "rabbitmq-instance-{{ branch }}"
